# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow checks out code, builds an image, performs a container image
# scan with Anchore's Syft tool, and uploads the results to the GitHub Dependency
# submission API.

# For more information on the Anchore sbom-action usage
# and parameters, see https://github.com/anchore/sbom-action. For more
# information about the Anchore SBOM tool, Syft, see
# https://github.com/anchore/syft
name: Anchore Syft SBOM Generator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-generate-sbom:
    runs-on: ubuntu-latest

    container:
      image: ros:humble

    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y \
            curl \
            git \
            python3-colcon-common-extensions \
            python3-rosdep \
            lsb-release \
            gnupg2 \
            sudo

      - name: Initialize rosdep
        run: |
          rosdep update || true

      - name: Checkout MoveIt2 source
        uses: actions/checkout@v4

      - name: Install ROS 2 dependencies with rosdep
        run: |
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build MoveIt2 workspace
        run: |
          colcon build --symlink-install

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Syft on install/ directory
        run: |
          syft dir:install/ -o cyclonedx-json > moveit2_sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: moveit2-sbom
          path: moveit2_sbom.json
